#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

if [[ $(xrandr -q | grep 'HDMI-1 connected') ]]; then
    xrandr --output eDP-1 --mode 1920x1200 --pos 3840x773 --rotate normal --output HDMI-1 --primary --mode 3840x2160 --pos 0x0 --rotate normal --output DP-1 --off --output DP-2 --off --output DP-3 --off --output DP-4 --off
fi

bspc monitor HDMI-1 -d I II III IV V
bspc monitor eDP-1 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Start Applications automatically
sxkhd &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
polybar &
